# Generated by Django 5.1rc1 on 2024-08-20 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('maximum_order_units', models.BigIntegerField()),
                ('margin_rate', models.CharField(max_length=20)),
                ('minimum_trade_size', models.CharField(max_length=20)),
                ('pip_location', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('open_date', models.DateTimeField(auto_now_add=True)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('bot', models.BooleanField(default=False)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('trade_type', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.instrument')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='accounts.profile')),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='trading.strategy')),
            ],
        ),
    ]
