# Generated by Django 5.0.6 on 2024-07-02 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
