# Generated by Django 5.1rc1 on 2024-08-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='realized_pl',
        ),
    ]
