# Generated by Django 5.1rc1 on 2024-08-18 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_profile_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unrealized_pl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('realized_pl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=10)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'ordering': ['-open_date'],
            },
        ),
    ]
