# Generated by Django 5.1rc1 on 2024-08-20 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unrealized_pl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('realized_pl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('strategy', models.CharField(default='moving_average', max_length=50)),
                ('instrument', models.CharField(default='EUR_USD', max_length=20)),
                ('short_ma_period', models.PositiveIntegerField(default=9)),
                ('long_ma_period', models.PositiveIntegerField(default=26)),
                ('granularity', models.CharField(default='H1', max_length=10)),
                ('prev_short_ma', models.FloatField(blank=True, null=True)),
                ('prev_long_ma', models.FloatField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
