# Generated by Django 5.1rc1 on 2024-08-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounthistory',
            name='unrealized_pl',
        ),
    ]
