# Generated by Django 5.1rc1 on 2024-08-20 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_accounthistory_unrealized_pl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounthistory',
            name='equity',
        ),
    ]
